version: "2"

volumes:
  postgres_data:

services:
  db:
    env_file:
      - .env
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    restart: always
    image: postgres:12
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgres://${DB_USER}:${DB_PASSWORD}@db/${DB_DATABASE}"
      DJANGO_MANAGEPY_MIGRATE: "on"
      DJANGO_MANAGEPY_COLLECTSTATIC: "on"
      DB_HOST: db
      MEDIA_ROOT: "/media/app/"
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    depends_on:
      - db
    ports:
      - "127.0.0.1:${PROD_PORT}:8000"
    volumes:
      - ./media:/media/app/
      - ./docker/docker-entrypoint.sh:/app/docker/docker-entrypoint.sh
      - ./:/app/
    extra_hosts:
      - "host.docker.internal:host-gateway"

